#!/usr/bin/env python3
"""Regenerate emoji.js from Unicode's emoji-test.txt and CLDR's English annotations.

Keeps only sequences the installed emoji font draws as a single glyph, folds
uniform skin-tone variants into their base emoji, and tags each emoji with its
popularity tier from Unicode's frequency survey (0 = most used).

    python gen-emoji.py [--font /usr/share/fonts/noto/NotoColorEmoji.ttf]
"""

import argparse
import html
import json
import re
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

from fontTools.ttLib import TTFont

EMOJI_TEST = "https://unicode.org/Public/emoji/latest/emoji-test.txt"
CLDR = "https://raw.githubusercontent.com/unicode-org/cldr/main/common/{}/en.xml"
FREQUENCY = "https://home.unicode.org/emoji/emoji-frequency/"
TONES = [0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF]
SKIP_GROUPS = {"Component"}
LINE = re.compile(r"^([0-9A-F ]+);\s*fully-qualified\s*#\s*\S+\s+E[\d.]+\s+(.*)$")


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read().decode()


def annotations():
    words = {}
    for kind in ("annotations", "annotationsDerived"):
        root = ET.fromstring(fetch(CLDR.format(kind)))
        for a in root.iter("annotation"):
            if a.get("type") == "tts":
                continue
            key = a.get("cp").replace("️", "")
            words.setdefault(key, [w.strip().lower() for w in a.text.split("|")])
    return words


def popularity():
    page = fetch(FREQUENCY)
    table = page[page.find("<table"):page.find("</table>")]
    tiers = {}
    for tier, cell in re.findall(r"<tr>\s*<td[^>]*>(\d+)</td>\s*<td[^>]*>(.*?)</td>", table, re.S):
        for e in html.unescape(re.sub(r"<[^>]+>", "", cell)).split():
            tiers.setdefault(e.replace("\ufe0f", ""), int(tier))
    return tiers


def renderable(path):
    font = TTFont(path)
    cmap = font.getBestCmap()
    ligatures = set()
    for lookup in font["GSUB"].table.LookupList.Lookup:
        for sub in lookup.SubTable:
            sub = sub.ExtSubTable if lookup.LookupType == 7 else sub
            for first, ligs in getattr(sub, "ligatures", {}).items():
                ligatures.update((first, *l.Component) for l in ligs)

    def check(cps):
        core = [c for c in cps if c != 0xFE0F]
        if any(c not in cmap for c in core):
            return False
        if len(core) == 1:
            return True
        return tuple(cmap[c] for c in core) in ligatures or tuple(cmap[c] for c in cps if c in cmap) in ligatures

    return check


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default="/usr/share/fonts/noto/NotoColorEmoji.ttf")
    args = ap.parse_args()

    ok = renderable(args.font)
    words = annotations()
    tiers = popularity()
    unranked = max(tiers.values()) + 1
    groups, bases, group = [], {}, None

    for line in fetch(EMOJI_TEST).splitlines():
        if line.startswith("# group:"):
            name = line.split(":", 1)[1].strip()
            group = None if name in SKIP_GROUPS else {"name": name.lower(), "emoji": []}
            if group:
                groups.append(group)
            continue
        m = LINE.match(line)
        if not m or group is None:
            continue
        cps = [int(c, 16) for c in m.group(1).split()]
        if not ok(cps):
            continue
        char = "".join(map(chr, cps))
        tones = [c for c in cps if c in TONES]
        stripped = "".join(chr(c) for c in cps if c not in TONES and c != 0xFE0F)
        if tones:
            base = bases.get(stripped)
            if base is not None and len(set(tones)) == 1:
                base.setdefault("tones", [None] * 5)[TONES.index(tones[0])] = char
            continue
        name = m.group(2).lower()
        keywords = [w for w in words.get(stripped, []) if w != name]
        if len(cps) == 2 and all(0x1F1E6 <= c <= 0x1F1FF for c in cps):
            keywords.insert(0, "".join(chr(c - 0x1F1E6 + ord("a")) for c in cps))
        entry = {"char": char, "name": name, "keywords": keywords, "tier": tiers.get(stripped, unranked)}
        bases[stripped] = entry
        group["emoji"].append(entry)

    rows = []
    for g in groups:
        items = []
        for e in g["emoji"]:
            row = [e["char"], e["name"], " | ".join(e["keywords"]), e["tier"]]
            tones = e.get("tones")
            if tones and all(tones):
                row.append(tones)
            items.append(row)
        rows.append({"name": g["name"], "emoji": items})

    out = Path(__file__).with_name("emoji.js")
    body = ",\n".join(json.dumps(g, ensure_ascii=False, separators=(",", ":")) for g in rows)
    notice = (
        "// Generated by gen-emoji.py from Unicode's emoji-test.txt, CLDR annotations and emoji frequency data.\n"
        "// Copyright © 1991-2026 Unicode, Inc. Distributed under the Unicode License v3:\n"
        "// https://www.unicode.org/license.txt\n"
    )
    out.write_text(f".pragma library\n\n{notice}\nvar groups = [\n{body}\n];\n")
    print(f"{out}: {sum(len(g['emoji']) for g in rows)} emoji in {len(rows)} groups")


if __name__ == "__main__":
    main()
