wallpaper {
    monitor = DP-1
    path = /home/max/media/picture/wallpaper-sky.png
}

wallpaper {
    monitor = DP-3
    path = /home/max/media/picture/20230629.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/max/media/picture/20230811.jpg
}
